{
  delib,
  lib,
  config,
  ...
}:
delib.module {
  name = "programs.ganymede";

  options = delib.singleEnableOption false;

  nixos.ifEnabled = {
    # Auto-generated by compose2nix.
    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
    };

    # Enable container name DNS for all Podman networks.
    networking.firewall.interfaces =
      let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in
      {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

    virtualisation.oci-containers.backend = "podman";

    # Containers
    virtualisation.oci-containers.containers."ganymede" = {
      image = "ghcr.io/zibbp/ganymede:latest";
      environment = {
        "CONFIG_DIR" = "/data/config";
        "DB_HOST" = "ganymede-db";
        "DB_NAME" = "ganymede-prd";
        "DB_PASS" = "PASSWORD";
        "DB_PORT" = "5432";
        "DB_SSL" = "disable";
        "DB_USER" = "ganymede";
        "DEBUG" = "false";
        "FORCE_SSO_AUTH" = "false";
        "LOGS_DIR" = "/data/logs";
        "MAX_CHAT_DOWNLOAD_EXECUTIONS" = "3";
        "MAX_CHAT_RENDER_EXECUTIONS" = "2";
        "MAX_VIDEO_CONVERT_EXECUTIONS" = "3";
        "MAX_VIDEO_DOWNLOAD_EXECUTIONS" = "2";
        "MAX_VIDEO_SPRITE_THUMBNAIL_EXECUTIONS" = "2";
        "REQUIRE_LOGIN" = "false";
        "SHOW_SSO_LOGIN_BUTTON" = "true";
        "TEMP_DIR" = "/data/temp";
        "TWITCH_CLIENT_ID" = "";
        "TWITCH_CLIENT_SECRET" = "";
        "TZ" = "America/Chicago";
        "VIDEOS_DIR" = "/data/videos";
      };
      volumes = [
        "/home/fishy/Projects/ganymede/config:/data/config:rw"
        "/home/fishy/Projects/ganymede/logs:/data/logs:rw"
        "/home/fishy/Projects/ganymede/temp:/data/temp:rw"
        "/path/to/vod/storage:/data/videos:rw"
      ];
      ports = [
        "4800:4000/tcp"
      ];
      dependsOn = [
        "ganymede-db"
      ];
      log-driver = "journald";
      extraOptions = [
        "--health-cmd=curl --fail http://localhost:4000/health || exit 1"
        "--health-interval=1m0s"
        "--health-retries=5"
        "--health-start-period=1m0s"
        "--health-timeout=10s"
        "--network-alias=ganymede"
        "--network=ganymede_default"
      ];
    };
    systemd.services."podman-ganymede" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-ganymede_default.service"
      ];
      requires = [
        "podman-network-ganymede_default.service"
      ];
      partOf = [
        "podman-compose-ganymede-root.target"
      ];
      wantedBy = [
        "podman-compose-ganymede-root.target"
      ];
    };
    virtualisation.oci-containers.containers."ganymede-db" = {
      image = "postgres:14";
      environment = {
        "POSTGRES_DB" = "ganymede-prd";
        "POSTGRES_PASSWORD" = "PASSWORD";
        "POSTGRES_USER" = "ganymede";
      };
      volumes = [
        "/home/fishy/Projects/ganymede/ganymede-db:/var/lib/postgresql/data:rw"
      ];
      ports = [
        "4801:5432/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--health-cmd=pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"
        "--health-interval=30s"
        "--health-retries=5"
        "--health-start-period=1m0s"
        "--health-timeout=1m0s"
        "--network-alias=ganymede-db"
        "--network=ganymede_default"
      ];
    };
    systemd.services."podman-ganymede-db" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-ganymede_default.service"
      ];
      requires = [
        "podman-network-ganymede_default.service"
      ];
      partOf = [
        "podman-compose-ganymede-root.target"
      ];
      wantedBy = [
        "podman-compose-ganymede-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-ganymede_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f ganymede_default";
      };
      script = ''
        podman network inspect ganymede_default || podman network create ganymede_default
      '';
      partOf = [ "podman-compose-ganymede-root.target" ];
      wantedBy = [ "podman-compose-ganymede-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-ganymede-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
